/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 4.9 */
/* /usr/local/diamond/3.13/ispfpga/bin/lin64/scuba -w -n multi_12bit -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type dspmult -simple_portname -pfu_mult -widtha 12 -widthb 12 -widthp 24 -signed -PL_stages 1 -output_reg -clk0 -ce0 -rst0  */
/* Fri Sep 27 09:44:37 2024 */


`timescale 1 ns / 1 ps
module multi_12bit (Clock, ClkEn, Aclr, DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Aclr;
    input wire [11:0] DataA;
    input wire [11:0] DataB;
    output wire [23:0] Result;

    wire rego_o_0;
    wire rego_o_1;
    wire rego_o_2;
    wire rego_o_3;
    wire rego_o_4;
    wire rego_o_5;
    wire rego_o_6;
    wire rego_o_7;
    wire f_multi_12bit_0_pp_0_0;
    wire multi_12bit_0_pp_0_0;
    wire f_multi_12bit_0_pp_0_1;
    wire f_s_multi_12bit_0_0_2;
    wire f_s_multi_12bit_0_0_3;
    wire multi_12bit_0_pp_2_4;
    wire multi_12bit_0_pp_4_8;
    wire s_multi_12bit_0_0_2;
    wire multi_12bit_0_pp_1_2;
    wire s_multi_12bit_0_0_3;
    wire s_multi_12bit_0_0_4;
    wire co_multi_12bit_0_0_1;
    wire s_multi_12bit_0_0_5;
    wire s_multi_12bit_0_0_6;
    wire co_multi_12bit_0_0_2;
    wire s_multi_12bit_0_0_7;
    wire s_multi_12bit_0_0_8;
    wire co_multi_12bit_0_0_3;
    wire s_multi_12bit_0_0_9;
    wire s_multi_12bit_0_0_10;
    wire co_multi_12bit_0_0_4;
    wire s_multi_12bit_0_0_11;
    wire s_multi_12bit_0_0_12;
    wire co_multi_12bit_0_0_5;
    wire s_multi_12bit_0_0_13;
    wire s_multi_12bit_0_0_14;
    wire co_multi_12bit_0_0_6;
    wire multi_12bit_0_pp_0_13;
    wire s_multi_12bit_0_0_15;
    wire s_multi_12bit_0_0_16;
    wire co_multi_12bit_0_0_7;
    wire multi_12bit_0_pp_1_15;
    wire s_multi_12bit_0_0_17;
    wire co_multi_12bit_0_0_8;
    wire s_multi_12bit_0_1_6;
    wire multi_12bit_0_pp_3_6;
    wire s_multi_12bit_0_1_7;
    wire s_multi_12bit_0_1_8;
    wire co_multi_12bit_0_1_1;
    wire s_multi_12bit_0_1_9;
    wire s_multi_12bit_0_1_10;
    wire co_multi_12bit_0_1_2;
    wire s_multi_12bit_0_1_11;
    wire s_multi_12bit_0_1_12;
    wire co_multi_12bit_0_1_3;
    wire s_multi_12bit_0_1_13;
    wire s_multi_12bit_0_1_14;
    wire co_multi_12bit_0_1_4;
    wire s_multi_12bit_0_1_15;
    wire s_multi_12bit_0_1_16;
    wire co_multi_12bit_0_1_5;
    wire s_multi_12bit_0_1_17;
    wire s_multi_12bit_0_1_18;
    wire co_multi_12bit_0_1_6;
    wire multi_12bit_0_pp_2_17;
    wire s_multi_12bit_0_1_19;
    wire s_multi_12bit_0_1_20;
    wire co_multi_12bit_0_1_7;
    wire multi_12bit_0_pp_3_19;
    wire s_multi_12bit_0_1_21;
    wire co_multi_12bit_0_1_8;
    wire s_multi_12bit_0_2_10;
    wire multi_12bit_0_pp_5_10;
    wire s_multi_12bit_0_2_11;
    wire s_multi_12bit_0_2_12;
    wire co_multi_12bit_0_2_1;
    wire s_multi_12bit_0_2_13;
    wire s_multi_12bit_0_2_14;
    wire co_multi_12bit_0_2_2;
    wire s_multi_12bit_0_2_15;
    wire s_multi_12bit_0_2_16;
    wire co_multi_12bit_0_2_3;
    wire s_multi_12bit_0_2_17;
    wire s_multi_12bit_0_2_18;
    wire co_multi_12bit_0_2_4;
    wire s_multi_12bit_0_2_19;
    wire s_multi_12bit_0_2_20;
    wire co_multi_12bit_0_2_5;
    wire s_multi_12bit_0_2_21;
    wire s_multi_12bit_0_2_22;
    wire co_multi_12bit_0_2_6;
    wire multi_12bit_0_pp_4_21;
    wire s_multi_12bit_0_2_23;
    wire co_multi_12bit_0_2_8;
    wire co_multi_12bit_0_2_7;
    wire multi_12bit_0_pp_5_23;
    wire s_multi_12bit_0_3_4;
    wire f_multi_12bit_0_pp_2_4;
    wire f_s_multi_12bit_0_0_4;
    wire s_multi_12bit_0_3_5;
    wire s_multi_12bit_0_3_6;
    wire co_multi_12bit_0_3_1;
    wire f_multi_12bit_0_pp_2_5;
    wire f_s_multi_12bit_0_1_6;
    wire f_s_multi_12bit_0_0_5;
    wire f_s_multi_12bit_0_0_6;
    wire s_multi_12bit_0_3_7;
    wire co_multi_12bit_0_3_2;
    wire f_s_multi_12bit_0_1_7;
    wire f_s_multi_12bit_0_1_8;
    wire f_s_multi_12bit_0_0_7;
    wire f_s_multi_12bit_0_0_8;
    wire co_multi_12bit_0_3_3;
    wire f_s_multi_12bit_0_1_9;
    wire f_s_multi_12bit_0_1_10;
    wire f_s_multi_12bit_0_0_9;
    wire f_s_multi_12bit_0_0_10;
    wire co_multi_12bit_0_3_4;
    wire f_s_multi_12bit_0_1_11;
    wire f_s_multi_12bit_0_1_12;
    wire f_s_multi_12bit_0_0_11;
    wire f_s_multi_12bit_0_0_12;
    wire co_multi_12bit_0_3_5;
    wire f_s_multi_12bit_0_1_13;
    wire f_s_multi_12bit_0_1_14;
    wire f_s_multi_12bit_0_0_13;
    wire f_s_multi_12bit_0_0_14;
    wire co_multi_12bit_0_3_6;
    wire f_s_multi_12bit_0_1_15;
    wire f_s_multi_12bit_0_1_16;
    wire f_s_multi_12bit_0_0_15;
    wire f_s_multi_12bit_0_0_16;
    wire co_multi_12bit_0_3_7;
    wire f_s_multi_12bit_0_1_17;
    wire f_s_multi_12bit_0_1_18;
    wire f_s_multi_12bit_0_0_17;
    wire co_multi_12bit_0_3_8;
    wire f_s_multi_12bit_0_1_19;
    wire f_s_multi_12bit_0_1_20;
    wire co_multi_12bit_0_3_9;
    wire f_s_multi_12bit_0_1_21;
    wire co_multi_12bit_0_3_10;
    wire rego_o_8;
    wire f_multi_12bit_0_pp_4_8;
    wire s_multi_12bit_0_3_8;
    wire rego_o_9;
    wire rego_o_10;
    wire co_t_multi_12bit_0_4_1;
    wire f_multi_12bit_0_pp_4_9;
    wire f_s_multi_12bit_0_2_10;
    wire s_multi_12bit_0_3_9;
    wire s_multi_12bit_0_3_10;
    wire rego_o_11;
    wire rego_o_12;
    wire co_t_multi_12bit_0_4_2;
    wire f_s_multi_12bit_0_2_11;
    wire f_s_multi_12bit_0_2_12;
    wire s_multi_12bit_0_3_11;
    wire s_multi_12bit_0_3_12;
    wire rego_o_13;
    wire rego_o_14;
    wire co_t_multi_12bit_0_4_3;
    wire f_s_multi_12bit_0_2_13;
    wire f_s_multi_12bit_0_2_14;
    wire s_multi_12bit_0_3_13;
    wire s_multi_12bit_0_3_14;
    wire rego_o_15;
    wire rego_o_16;
    wire co_t_multi_12bit_0_4_4;
    wire f_s_multi_12bit_0_2_15;
    wire f_s_multi_12bit_0_2_16;
    wire s_multi_12bit_0_3_15;
    wire s_multi_12bit_0_3_16;
    wire rego_o_17;
    wire rego_o_18;
    wire co_t_multi_12bit_0_4_5;
    wire f_s_multi_12bit_0_2_17;
    wire f_s_multi_12bit_0_2_18;
    wire s_multi_12bit_0_3_17;
    wire s_multi_12bit_0_3_18;
    wire rego_o_19;
    wire rego_o_20;
    wire co_t_multi_12bit_0_4_6;
    wire f_s_multi_12bit_0_2_19;
    wire f_s_multi_12bit_0_2_20;
    wire s_multi_12bit_0_3_19;
    wire s_multi_12bit_0_3_20;
    wire rego_o_21;
    wire rego_o_22;
    wire co_t_multi_12bit_0_4_7;
    wire f_s_multi_12bit_0_2_21;
    wire f_s_multi_12bit_0_2_22;
    wire s_multi_12bit_0_3_21;
    wire s_multi_12bit_0_3_22;
    wire rego_o_23;
    wire co_t_multi_12bit_0_4_9;
    wire co_t_multi_12bit_0_4_8;
    wire f_s_multi_12bit_0_2_23;
    wire s_multi_12bit_0_3_23;
    wire multi_12bit_0_pp_0_2;
    wire multi_12bit_0_pp_0_1;
    wire multi_12bit_0_cin_lr_0;
    wire multi_12bit_0_pp_0_4;
    wire multi_12bit_0_pp_0_3;
    wire mco;
    wire multi_12bit_0_pp_0_6;
    wire multi_12bit_0_pp_0_5;
    wire mco_1;
    wire multi_12bit_0_pp_0_8;
    wire multi_12bit_0_pp_0_7;
    wire mco_2;
    wire multi_12bit_0_pp_0_10;
    wire multi_12bit_0_pp_0_9;
    wire mco_3;
    wire mfco;
    wire multi_12bit_0_pp_0_12;
    wire multi_12bit_0_pp_0_11;
    wire mco_4;
    wire multi_12bit_0_mult_0_5_n1;
    wire multi_12bit_0_mult_0_5_n2;
    wire multi_12bit_0_pp_1_4;
    wire multi_12bit_0_pp_1_3;
    wire multi_12bit_0_cin_lr_2;
    wire multi_12bit_0_pp_1_6;
    wire multi_12bit_0_pp_1_5;
    wire mco_5;
    wire multi_12bit_0_pp_1_8;
    wire multi_12bit_0_pp_1_7;
    wire mco_6;
    wire multi_12bit_0_pp_1_10;
    wire multi_12bit_0_pp_1_9;
    wire mco_7;
    wire multi_12bit_0_pp_1_12;
    wire multi_12bit_0_pp_1_11;
    wire mco_8;
    wire mfco_1;
    wire multi_12bit_0_pp_1_14;
    wire multi_12bit_0_pp_1_13;
    wire mco_9;
    wire multi_12bit_0_mult_2_5_n1;
    wire multi_12bit_0_mult_2_5_n2;
    wire multi_12bit_0_pp_2_6;
    wire multi_12bit_0_pp_2_5;
    wire multi_12bit_0_cin_lr_4;
    wire multi_12bit_0_pp_2_8;
    wire multi_12bit_0_pp_2_7;
    wire mco_10;
    wire multi_12bit_0_pp_2_10;
    wire multi_12bit_0_pp_2_9;
    wire mco_11;
    wire multi_12bit_0_pp_2_12;
    wire multi_12bit_0_pp_2_11;
    wire mco_12;
    wire multi_12bit_0_pp_2_14;
    wire multi_12bit_0_pp_2_13;
    wire mco_13;
    wire mfco_2;
    wire multi_12bit_0_pp_2_16;
    wire multi_12bit_0_pp_2_15;
    wire mco_14;
    wire multi_12bit_0_mult_4_5_n1;
    wire multi_12bit_0_mult_4_5_n2;
    wire multi_12bit_0_pp_3_8;
    wire multi_12bit_0_pp_3_7;
    wire multi_12bit_0_cin_lr_6;
    wire multi_12bit_0_pp_3_10;
    wire multi_12bit_0_pp_3_9;
    wire mco_15;
    wire multi_12bit_0_pp_3_12;
    wire multi_12bit_0_pp_3_11;
    wire mco_16;
    wire multi_12bit_0_pp_3_14;
    wire multi_12bit_0_pp_3_13;
    wire mco_17;
    wire multi_12bit_0_pp_3_16;
    wire multi_12bit_0_pp_3_15;
    wire mco_18;
    wire mfco_3;
    wire multi_12bit_0_pp_3_18;
    wire multi_12bit_0_pp_3_17;
    wire mco_19;
    wire multi_12bit_0_mult_6_5_n1;
    wire multi_12bit_0_mult_6_5_n2;
    wire multi_12bit_0_pp_4_10;
    wire multi_12bit_0_pp_4_9;
    wire multi_12bit_0_cin_lr_8;
    wire multi_12bit_0_pp_4_12;
    wire multi_12bit_0_pp_4_11;
    wire mco_20;
    wire multi_12bit_0_pp_4_14;
    wire multi_12bit_0_pp_4_13;
    wire mco_21;
    wire multi_12bit_0_pp_4_16;
    wire multi_12bit_0_pp_4_15;
    wire mco_22;
    wire multi_12bit_0_pp_4_18;
    wire multi_12bit_0_pp_4_17;
    wire mco_23;
    wire mfco_4;
    wire multi_12bit_0_pp_4_20;
    wire multi_12bit_0_pp_4_19;
    wire mco_24;
    wire multi_12bit_0_mult_8_5_n1;
    wire multi_12bit_0_mult_8_5_n2;
    wire multi_12bit_0_pp_5_12;
    wire multi_12bit_0_pp_5_11;
    wire multi_12bit_0_cin_lr_10;
    wire multi_12bit_0_mult_10_0_n1;
    wire multi_12bit_0_mult_10_0_n0;
    wire multi_12bit_0_pp_5_14;
    wire multi_12bit_0_pp_5_13;
    wire mco_25;
    wire multi_12bit_0_mult_10_1_n1;
    wire multi_12bit_0_mult_10_1_n0;
    wire multi_12bit_0_pp_5_16;
    wire multi_12bit_0_pp_5_15;
    wire mco_26;
    wire multi_12bit_0_mult_10_2_n1;
    wire multi_12bit_0_mult_10_2_n0;
    wire multi_12bit_0_pp_5_18;
    wire multi_12bit_0_pp_5_17;
    wire mco_27;
    wire multi_12bit_0_mult_10_3_n1;
    wire multi_12bit_0_mult_10_3_n0;
    wire multi_12bit_0_pp_5_20;
    wire multi_12bit_0_pp_5_19;
    wire mco_28;
    wire multi_12bit_0_mult_10_4_n1;
    wire multi_12bit_0_mult_10_4_n0;
    wire mfco_5;
    wire multi_12bit_0_pp_5_22;
    wire multi_12bit_0_pp_5_21;
    wire mco_29;
    wire scuba_vlo;
    wire multi_12bit_0_mult_10_5_n2;
    wire scuba_vhi;
    wire multi_12bit_0_mult_10_5_n0;

    AND2 AND2_t27 (.A(DataA[0]), .B(DataB[0]), .Z(multi_12bit_0_pp_0_0));

    ND2 ND2_t26 (.A(DataA[11]), .B(DataB[0]), .Z(multi_12bit_0_mult_0_5_n2));

    ND2 ND2_t25 (.A(DataA[11]), .B(DataB[1]), .Z(multi_12bit_0_mult_0_5_n1));

    AND2 AND2_t24 (.A(DataA[0]), .B(DataB[2]), .Z(multi_12bit_0_pp_1_2));

    ND2 ND2_t23 (.A(DataA[11]), .B(DataB[2]), .Z(multi_12bit_0_mult_2_5_n2));

    ND2 ND2_t22 (.A(DataA[11]), .B(DataB[3]), .Z(multi_12bit_0_mult_2_5_n1));

    AND2 AND2_t21 (.A(DataA[0]), .B(DataB[4]), .Z(multi_12bit_0_pp_2_4));

    ND2 ND2_t20 (.A(DataA[11]), .B(DataB[4]), .Z(multi_12bit_0_mult_4_5_n2));

    ND2 ND2_t19 (.A(DataA[11]), .B(DataB[5]), .Z(multi_12bit_0_mult_4_5_n1));

    AND2 AND2_t18 (.A(DataA[0]), .B(DataB[6]), .Z(multi_12bit_0_pp_3_6));

    ND2 ND2_t17 (.A(DataA[11]), .B(DataB[6]), .Z(multi_12bit_0_mult_6_5_n2));

    ND2 ND2_t16 (.A(DataA[11]), .B(DataB[7]), .Z(multi_12bit_0_mult_6_5_n1));

    AND2 AND2_t15 (.A(DataA[0]), .B(DataB[8]), .Z(multi_12bit_0_pp_4_8));

    ND2 ND2_t14 (.A(DataA[11]), .B(DataB[8]), .Z(multi_12bit_0_mult_8_5_n2));

    ND2 ND2_t13 (.A(DataA[11]), .B(DataB[9]), .Z(multi_12bit_0_mult_8_5_n1));

    AND2 AND2_t12 (.A(DataA[0]), .B(DataB[10]), .Z(multi_12bit_0_pp_5_10));

    ND2 ND2_t11 (.A(DataA[1]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_0_n1));

    ND2 ND2_t10 (.A(DataA[0]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_0_n0));

    ND2 ND2_t9 (.A(DataA[3]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_1_n1));

    ND2 ND2_t8 (.A(DataA[2]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_1_n0));

    ND2 ND2_t7 (.A(DataA[5]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_2_n1));

    ND2 ND2_t6 (.A(DataA[4]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_2_n0));

    ND2 ND2_t5 (.A(DataA[7]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_3_n1));

    ND2 ND2_t4 (.A(DataA[6]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_3_n0));

    ND2 ND2_t3 (.A(DataA[9]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_4_n1));

    ND2 ND2_t2 (.A(DataA[8]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_4_n0));

    ND2 ND2_t1 (.A(DataA[11]), .B(DataB[10]), .Z(multi_12bit_0_mult_10_5_n2));

    ND2 ND2_t0 (.A(DataA[10]), .B(DataB[11]), .Z(multi_12bit_0_mult_10_5_n0));

    FD1P3DX FF_75 (.D(rego_o_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_74 (.D(rego_o_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_73 (.D(rego_o_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_72 (.D(rego_o_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_71 (.D(rego_o_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_70 (.D(rego_o_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_69 (.D(rego_o_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_68 (.D(rego_o_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_67 (.D(rego_o_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_66 (.D(rego_o_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_65 (.D(rego_o_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_64 (.D(rego_o_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_63 (.D(rego_o_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_62 (.D(rego_o_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_61 (.D(rego_o_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_60 (.D(rego_o_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_59 (.D(rego_o_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[16]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_58 (.D(rego_o_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[17]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_57 (.D(rego_o_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[18]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_56 (.D(rego_o_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[19]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_55 (.D(rego_o_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[20]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_54 (.D(rego_o_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[21]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_53 (.D(rego_o_22), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[22]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_52 (.D(rego_o_23), .SP(ClkEn), .CK(Clock), .CD(Aclr), .Q(Result[23]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_51 (.D(multi_12bit_0_pp_0_0), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multi_12bit_0_pp_0_0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_50 (.D(multi_12bit_0_pp_0_1), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multi_12bit_0_pp_0_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_49 (.D(s_multi_12bit_0_0_2), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_48 (.D(s_multi_12bit_0_0_3), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_47 (.D(s_multi_12bit_0_0_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_46 (.D(s_multi_12bit_0_0_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_45 (.D(s_multi_12bit_0_0_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_44 (.D(s_multi_12bit_0_0_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_43 (.D(s_multi_12bit_0_0_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_42 (.D(s_multi_12bit_0_0_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_41 (.D(s_multi_12bit_0_0_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_40 (.D(s_multi_12bit_0_0_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_39 (.D(s_multi_12bit_0_0_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_38 (.D(s_multi_12bit_0_0_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_37 (.D(s_multi_12bit_0_0_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_36 (.D(s_multi_12bit_0_0_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_35 (.D(s_multi_12bit_0_0_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_34 (.D(s_multi_12bit_0_0_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_0_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_33 (.D(multi_12bit_0_pp_2_4), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multi_12bit_0_pp_2_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_32 (.D(multi_12bit_0_pp_2_5), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multi_12bit_0_pp_2_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_31 (.D(s_multi_12bit_0_1_6), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(s_multi_12bit_0_1_7), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(s_multi_12bit_0_1_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(s_multi_12bit_0_1_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(s_multi_12bit_0_1_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(s_multi_12bit_0_1_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(s_multi_12bit_0_1_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(s_multi_12bit_0_1_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(s_multi_12bit_0_1_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(s_multi_12bit_0_1_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(s_multi_12bit_0_1_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(s_multi_12bit_0_1_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(s_multi_12bit_0_1_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_18))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(s_multi_12bit_0_1_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_19))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(s_multi_12bit_0_1_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_20))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(s_multi_12bit_0_1_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_1_21))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(multi_12bit_0_pp_4_8), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multi_12bit_0_pp_4_8))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(multi_12bit_0_pp_4_9), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_multi_12bit_0_pp_4_9))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(s_multi_12bit_0_2_10), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_10))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(s_multi_12bit_0_2_11), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_11))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(s_multi_12bit_0_2_12), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_12))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(s_multi_12bit_0_2_13), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_13))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(s_multi_12bit_0_2_14), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_14))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(s_multi_12bit_0_2_15), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_15))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(s_multi_12bit_0_2_16), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_16))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(s_multi_12bit_0_2_17), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_17))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(s_multi_12bit_0_2_18), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_18))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(s_multi_12bit_0_2_19), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_19))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(s_multi_12bit_0_2_20), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_20))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(s_multi_12bit_0_2_21), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_21))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(s_multi_12bit_0_2_22), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_22))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(s_multi_12bit_0_2_23), .SP(ClkEn), .CK(Clock), .CD(Aclr), 
        .Q(f_s_multi_12bit_0_2_23))
             /* synthesis GSR="ENABLED" */;

    FADD2B multi_12bit_0_cin_lr_add_0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(multi_12bit_0_cin_lr_0), .S0(), 
        .S1());

    FADD2B multi_12bit_0_Cadd_0_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco), .COUT(), .S0(multi_12bit_0_pp_0_13), 
        .S1());

    FADD2B multi_12bit_0_cin_lr_add_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(multi_12bit_0_cin_lr_2), .S0(), 
        .S1());

    FADD2B multi_12bit_0_Cadd_2_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_1), .COUT(), .S0(multi_12bit_0_pp_1_15), 
        .S1());

    FADD2B multi_12bit_0_cin_lr_add_4 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(multi_12bit_0_cin_lr_4), .S0(), 
        .S1());

    FADD2B multi_12bit_0_Cadd_4_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_2), .COUT(), .S0(multi_12bit_0_pp_2_17), 
        .S1());

    FADD2B multi_12bit_0_cin_lr_add_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(multi_12bit_0_cin_lr_6), .S0(), 
        .S1());

    FADD2B multi_12bit_0_Cadd_6_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_3), .COUT(), .S0(multi_12bit_0_pp_3_19), 
        .S1());

    FADD2B multi_12bit_0_cin_lr_add_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(multi_12bit_0_cin_lr_8), .S0(), 
        .S1());

    FADD2B multi_12bit_0_Cadd_8_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_4), .COUT(), .S0(multi_12bit_0_pp_4_21), 
        .S1());

    FADD2B multi_12bit_0_cin_lr_add_10 (.A0(scuba_vlo), .A1(scuba_vlo), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(scuba_vlo), .COUT(multi_12bit_0_cin_lr_10), 
        .S0(), .S1());

    FADD2B multi_12bit_0_Cadd_10_6 (.A0(scuba_vhi), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_5), .COUT(), .S0(multi_12bit_0_pp_5_23), 
        .S1());

    FADD2B Cadd_multi_12bit_0_0_1 (.A0(scuba_vlo), .A1(multi_12bit_0_pp_0_2), 
        .B0(scuba_vlo), .B1(multi_12bit_0_pp_1_2), .CI(scuba_vlo), .COUT(co_multi_12bit_0_0_1), 
        .S0(), .S1(s_multi_12bit_0_0_2));

    FADD2B multi_12bit_0_add_0_2 (.A0(multi_12bit_0_pp_0_3), .A1(multi_12bit_0_pp_0_4), 
        .B0(multi_12bit_0_pp_1_3), .B1(multi_12bit_0_pp_1_4), .CI(co_multi_12bit_0_0_1), 
        .COUT(co_multi_12bit_0_0_2), .S0(s_multi_12bit_0_0_3), .S1(s_multi_12bit_0_0_4));

    FADD2B multi_12bit_0_add_0_3 (.A0(multi_12bit_0_pp_0_5), .A1(multi_12bit_0_pp_0_6), 
        .B0(multi_12bit_0_pp_1_5), .B1(multi_12bit_0_pp_1_6), .CI(co_multi_12bit_0_0_2), 
        .COUT(co_multi_12bit_0_0_3), .S0(s_multi_12bit_0_0_5), .S1(s_multi_12bit_0_0_6));

    FADD2B multi_12bit_0_add_0_4 (.A0(multi_12bit_0_pp_0_7), .A1(multi_12bit_0_pp_0_8), 
        .B0(multi_12bit_0_pp_1_7), .B1(multi_12bit_0_pp_1_8), .CI(co_multi_12bit_0_0_3), 
        .COUT(co_multi_12bit_0_0_4), .S0(s_multi_12bit_0_0_7), .S1(s_multi_12bit_0_0_8));

    FADD2B multi_12bit_0_add_0_5 (.A0(multi_12bit_0_pp_0_9), .A1(multi_12bit_0_pp_0_10), 
        .B0(multi_12bit_0_pp_1_9), .B1(multi_12bit_0_pp_1_10), .CI(co_multi_12bit_0_0_4), 
        .COUT(co_multi_12bit_0_0_5), .S0(s_multi_12bit_0_0_9), .S1(s_multi_12bit_0_0_10));

    FADD2B multi_12bit_0_add_0_6 (.A0(multi_12bit_0_pp_0_11), .A1(multi_12bit_0_pp_0_12), 
        .B0(multi_12bit_0_pp_1_11), .B1(multi_12bit_0_pp_1_12), .CI(co_multi_12bit_0_0_5), 
        .COUT(co_multi_12bit_0_0_6), .S0(s_multi_12bit_0_0_11), .S1(s_multi_12bit_0_0_12));

    FADD2B multi_12bit_0_add_0_7 (.A0(multi_12bit_0_pp_0_13), .A1(scuba_vlo), 
        .B0(multi_12bit_0_pp_1_13), .B1(multi_12bit_0_pp_1_14), .CI(co_multi_12bit_0_0_6), 
        .COUT(co_multi_12bit_0_0_7), .S0(s_multi_12bit_0_0_13), .S1(s_multi_12bit_0_0_14));

    FADD2B multi_12bit_0_add_0_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(multi_12bit_0_pp_1_15), 
        .B1(scuba_vlo), .CI(co_multi_12bit_0_0_7), .COUT(co_multi_12bit_0_0_8), 
        .S0(s_multi_12bit_0_0_15), .S1(s_multi_12bit_0_0_16));

    FADD2B Cadd_multi_12bit_0_0_9 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_multi_12bit_0_0_8), .COUT(), .S0(s_multi_12bit_0_0_17), 
        .S1());

    FADD2B Cadd_multi_12bit_0_1_1 (.A0(scuba_vlo), .A1(multi_12bit_0_pp_2_6), 
        .B0(scuba_vlo), .B1(multi_12bit_0_pp_3_6), .CI(scuba_vlo), .COUT(co_multi_12bit_0_1_1), 
        .S0(), .S1(s_multi_12bit_0_1_6));

    FADD2B multi_12bit_0_add_1_2 (.A0(multi_12bit_0_pp_2_7), .A1(multi_12bit_0_pp_2_8), 
        .B0(multi_12bit_0_pp_3_7), .B1(multi_12bit_0_pp_3_8), .CI(co_multi_12bit_0_1_1), 
        .COUT(co_multi_12bit_0_1_2), .S0(s_multi_12bit_0_1_7), .S1(s_multi_12bit_0_1_8));

    FADD2B multi_12bit_0_add_1_3 (.A0(multi_12bit_0_pp_2_9), .A1(multi_12bit_0_pp_2_10), 
        .B0(multi_12bit_0_pp_3_9), .B1(multi_12bit_0_pp_3_10), .CI(co_multi_12bit_0_1_2), 
        .COUT(co_multi_12bit_0_1_3), .S0(s_multi_12bit_0_1_9), .S1(s_multi_12bit_0_1_10));

    FADD2B multi_12bit_0_add_1_4 (.A0(multi_12bit_0_pp_2_11), .A1(multi_12bit_0_pp_2_12), 
        .B0(multi_12bit_0_pp_3_11), .B1(multi_12bit_0_pp_3_12), .CI(co_multi_12bit_0_1_3), 
        .COUT(co_multi_12bit_0_1_4), .S0(s_multi_12bit_0_1_11), .S1(s_multi_12bit_0_1_12));

    FADD2B multi_12bit_0_add_1_5 (.A0(multi_12bit_0_pp_2_13), .A1(multi_12bit_0_pp_2_14), 
        .B0(multi_12bit_0_pp_3_13), .B1(multi_12bit_0_pp_3_14), .CI(co_multi_12bit_0_1_4), 
        .COUT(co_multi_12bit_0_1_5), .S0(s_multi_12bit_0_1_13), .S1(s_multi_12bit_0_1_14));

    FADD2B multi_12bit_0_add_1_6 (.A0(multi_12bit_0_pp_2_15), .A1(multi_12bit_0_pp_2_16), 
        .B0(multi_12bit_0_pp_3_15), .B1(multi_12bit_0_pp_3_16), .CI(co_multi_12bit_0_1_5), 
        .COUT(co_multi_12bit_0_1_6), .S0(s_multi_12bit_0_1_15), .S1(s_multi_12bit_0_1_16));

    FADD2B multi_12bit_0_add_1_7 (.A0(multi_12bit_0_pp_2_17), .A1(scuba_vlo), 
        .B0(multi_12bit_0_pp_3_17), .B1(multi_12bit_0_pp_3_18), .CI(co_multi_12bit_0_1_6), 
        .COUT(co_multi_12bit_0_1_7), .S0(s_multi_12bit_0_1_17), .S1(s_multi_12bit_0_1_18));

    FADD2B multi_12bit_0_add_1_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(multi_12bit_0_pp_3_19), 
        .B1(scuba_vlo), .CI(co_multi_12bit_0_1_7), .COUT(co_multi_12bit_0_1_8), 
        .S0(s_multi_12bit_0_1_19), .S1(s_multi_12bit_0_1_20));

    FADD2B Cadd_multi_12bit_0_1_9 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_multi_12bit_0_1_8), .COUT(), .S0(s_multi_12bit_0_1_21), 
        .S1());

    FADD2B Cadd_multi_12bit_0_2_1 (.A0(scuba_vlo), .A1(multi_12bit_0_pp_4_10), 
        .B0(scuba_vlo), .B1(multi_12bit_0_pp_5_10), .CI(scuba_vlo), .COUT(co_multi_12bit_0_2_1), 
        .S0(), .S1(s_multi_12bit_0_2_10));

    FADD2B multi_12bit_0_add_2_2 (.A0(multi_12bit_0_pp_4_11), .A1(multi_12bit_0_pp_4_12), 
        .B0(multi_12bit_0_pp_5_11), .B1(multi_12bit_0_pp_5_12), .CI(co_multi_12bit_0_2_1), 
        .COUT(co_multi_12bit_0_2_2), .S0(s_multi_12bit_0_2_11), .S1(s_multi_12bit_0_2_12));

    FADD2B multi_12bit_0_add_2_3 (.A0(multi_12bit_0_pp_4_13), .A1(multi_12bit_0_pp_4_14), 
        .B0(multi_12bit_0_pp_5_13), .B1(multi_12bit_0_pp_5_14), .CI(co_multi_12bit_0_2_2), 
        .COUT(co_multi_12bit_0_2_3), .S0(s_multi_12bit_0_2_13), .S1(s_multi_12bit_0_2_14));

    FADD2B multi_12bit_0_add_2_4 (.A0(multi_12bit_0_pp_4_15), .A1(multi_12bit_0_pp_4_16), 
        .B0(multi_12bit_0_pp_5_15), .B1(multi_12bit_0_pp_5_16), .CI(co_multi_12bit_0_2_3), 
        .COUT(co_multi_12bit_0_2_4), .S0(s_multi_12bit_0_2_15), .S1(s_multi_12bit_0_2_16));

    FADD2B multi_12bit_0_add_2_5 (.A0(multi_12bit_0_pp_4_17), .A1(multi_12bit_0_pp_4_18), 
        .B0(multi_12bit_0_pp_5_17), .B1(multi_12bit_0_pp_5_18), .CI(co_multi_12bit_0_2_4), 
        .COUT(co_multi_12bit_0_2_5), .S0(s_multi_12bit_0_2_17), .S1(s_multi_12bit_0_2_18));

    FADD2B multi_12bit_0_add_2_6 (.A0(multi_12bit_0_pp_4_19), .A1(multi_12bit_0_pp_4_20), 
        .B0(multi_12bit_0_pp_5_19), .B1(multi_12bit_0_pp_5_20), .CI(co_multi_12bit_0_2_5), 
        .COUT(co_multi_12bit_0_2_6), .S0(s_multi_12bit_0_2_19), .S1(s_multi_12bit_0_2_20));

    FADD2B multi_12bit_0_add_2_7 (.A0(multi_12bit_0_pp_4_21), .A1(scuba_vlo), 
        .B0(multi_12bit_0_pp_5_21), .B1(multi_12bit_0_pp_5_22), .CI(co_multi_12bit_0_2_6), 
        .COUT(co_multi_12bit_0_2_7), .S0(s_multi_12bit_0_2_21), .S1(s_multi_12bit_0_2_22));

    FADD2B multi_12bit_0_add_2_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(multi_12bit_0_pp_5_23), 
        .B1(scuba_vlo), .CI(co_multi_12bit_0_2_7), .COUT(co_multi_12bit_0_2_8), 
        .S0(s_multi_12bit_0_2_23), .S1());

    FADD2B Cadd_multi_12bit_0_3_1 (.A0(scuba_vlo), .A1(f_s_multi_12bit_0_0_4), 
        .B0(scuba_vlo), .B1(f_multi_12bit_0_pp_2_4), .CI(scuba_vlo), .COUT(co_multi_12bit_0_3_1), 
        .S0(), .S1(s_multi_12bit_0_3_4));

    FADD2B multi_12bit_0_add_3_2 (.A0(f_s_multi_12bit_0_0_5), .A1(f_s_multi_12bit_0_0_6), 
        .B0(f_multi_12bit_0_pp_2_5), .B1(f_s_multi_12bit_0_1_6), .CI(co_multi_12bit_0_3_1), 
        .COUT(co_multi_12bit_0_3_2), .S0(s_multi_12bit_0_3_5), .S1(s_multi_12bit_0_3_6));

    FADD2B multi_12bit_0_add_3_3 (.A0(f_s_multi_12bit_0_0_7), .A1(f_s_multi_12bit_0_0_8), 
        .B0(f_s_multi_12bit_0_1_7), .B1(f_s_multi_12bit_0_1_8), .CI(co_multi_12bit_0_3_2), 
        .COUT(co_multi_12bit_0_3_3), .S0(s_multi_12bit_0_3_7), .S1(s_multi_12bit_0_3_8));

    FADD2B multi_12bit_0_add_3_4 (.A0(f_s_multi_12bit_0_0_9), .A1(f_s_multi_12bit_0_0_10), 
        .B0(f_s_multi_12bit_0_1_9), .B1(f_s_multi_12bit_0_1_10), .CI(co_multi_12bit_0_3_3), 
        .COUT(co_multi_12bit_0_3_4), .S0(s_multi_12bit_0_3_9), .S1(s_multi_12bit_0_3_10));

    FADD2B multi_12bit_0_add_3_5 (.A0(f_s_multi_12bit_0_0_11), .A1(f_s_multi_12bit_0_0_12), 
        .B0(f_s_multi_12bit_0_1_11), .B1(f_s_multi_12bit_0_1_12), .CI(co_multi_12bit_0_3_4), 
        .COUT(co_multi_12bit_0_3_5), .S0(s_multi_12bit_0_3_11), .S1(s_multi_12bit_0_3_12));

    FADD2B multi_12bit_0_add_3_6 (.A0(f_s_multi_12bit_0_0_13), .A1(f_s_multi_12bit_0_0_14), 
        .B0(f_s_multi_12bit_0_1_13), .B1(f_s_multi_12bit_0_1_14), .CI(co_multi_12bit_0_3_5), 
        .COUT(co_multi_12bit_0_3_6), .S0(s_multi_12bit_0_3_13), .S1(s_multi_12bit_0_3_14));

    FADD2B multi_12bit_0_add_3_7 (.A0(f_s_multi_12bit_0_0_15), .A1(f_s_multi_12bit_0_0_16), 
        .B0(f_s_multi_12bit_0_1_15), .B1(f_s_multi_12bit_0_1_16), .CI(co_multi_12bit_0_3_6), 
        .COUT(co_multi_12bit_0_3_7), .S0(s_multi_12bit_0_3_15), .S1(s_multi_12bit_0_3_16));

    FADD2B multi_12bit_0_add_3_8 (.A0(f_s_multi_12bit_0_0_17), .A1(scuba_vlo), 
        .B0(f_s_multi_12bit_0_1_17), .B1(f_s_multi_12bit_0_1_18), .CI(co_multi_12bit_0_3_7), 
        .COUT(co_multi_12bit_0_3_8), .S0(s_multi_12bit_0_3_17), .S1(s_multi_12bit_0_3_18));

    FADD2B multi_12bit_0_add_3_9 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(f_s_multi_12bit_0_1_19), 
        .B1(f_s_multi_12bit_0_1_20), .CI(co_multi_12bit_0_3_8), .COUT(co_multi_12bit_0_3_9), 
        .S0(s_multi_12bit_0_3_19), .S1(s_multi_12bit_0_3_20));

    FADD2B multi_12bit_0_add_3_10 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(f_s_multi_12bit_0_1_21), 
        .B1(scuba_vlo), .CI(co_multi_12bit_0_3_9), .COUT(co_multi_12bit_0_3_10), 
        .S0(s_multi_12bit_0_3_21), .S1(s_multi_12bit_0_3_22));

    FADD2B Cadd_multi_12bit_0_3_11 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_multi_12bit_0_3_10), .COUT(), .S0(s_multi_12bit_0_3_23), 
        .S1());

    FADD2B Cadd_t_multi_12bit_0_4_1 (.A0(scuba_vlo), .A1(s_multi_12bit_0_3_8), 
        .B0(scuba_vlo), .B1(f_multi_12bit_0_pp_4_8), .CI(scuba_vlo), .COUT(co_t_multi_12bit_0_4_1), 
        .S0(), .S1(rego_o_8));

    FADD2B t_multi_12bit_0_add_4_2 (.A0(s_multi_12bit_0_3_9), .A1(s_multi_12bit_0_3_10), 
        .B0(f_multi_12bit_0_pp_4_9), .B1(f_s_multi_12bit_0_2_10), .CI(co_t_multi_12bit_0_4_1), 
        .COUT(co_t_multi_12bit_0_4_2), .S0(rego_o_9), .S1(rego_o_10));

    FADD2B t_multi_12bit_0_add_4_3 (.A0(s_multi_12bit_0_3_11), .A1(s_multi_12bit_0_3_12), 
        .B0(f_s_multi_12bit_0_2_11), .B1(f_s_multi_12bit_0_2_12), .CI(co_t_multi_12bit_0_4_2), 
        .COUT(co_t_multi_12bit_0_4_3), .S0(rego_o_11), .S1(rego_o_12));

    FADD2B t_multi_12bit_0_add_4_4 (.A0(s_multi_12bit_0_3_13), .A1(s_multi_12bit_0_3_14), 
        .B0(f_s_multi_12bit_0_2_13), .B1(f_s_multi_12bit_0_2_14), .CI(co_t_multi_12bit_0_4_3), 
        .COUT(co_t_multi_12bit_0_4_4), .S0(rego_o_13), .S1(rego_o_14));

    FADD2B t_multi_12bit_0_add_4_5 (.A0(s_multi_12bit_0_3_15), .A1(s_multi_12bit_0_3_16), 
        .B0(f_s_multi_12bit_0_2_15), .B1(f_s_multi_12bit_0_2_16), .CI(co_t_multi_12bit_0_4_4), 
        .COUT(co_t_multi_12bit_0_4_5), .S0(rego_o_15), .S1(rego_o_16));

    FADD2B t_multi_12bit_0_add_4_6 (.A0(s_multi_12bit_0_3_17), .A1(s_multi_12bit_0_3_18), 
        .B0(f_s_multi_12bit_0_2_17), .B1(f_s_multi_12bit_0_2_18), .CI(co_t_multi_12bit_0_4_5), 
        .COUT(co_t_multi_12bit_0_4_6), .S0(rego_o_17), .S1(rego_o_18));

    FADD2B t_multi_12bit_0_add_4_7 (.A0(s_multi_12bit_0_3_19), .A1(s_multi_12bit_0_3_20), 
        .B0(f_s_multi_12bit_0_2_19), .B1(f_s_multi_12bit_0_2_20), .CI(co_t_multi_12bit_0_4_6), 
        .COUT(co_t_multi_12bit_0_4_7), .S0(rego_o_19), .S1(rego_o_20));

    FADD2B t_multi_12bit_0_add_4_8 (.A0(s_multi_12bit_0_3_21), .A1(s_multi_12bit_0_3_22), 
        .B0(f_s_multi_12bit_0_2_21), .B1(f_s_multi_12bit_0_2_22), .CI(co_t_multi_12bit_0_4_7), 
        .COUT(co_t_multi_12bit_0_4_8), .S0(rego_o_21), .S1(rego_o_22));

    FADD2B t_multi_12bit_0_add_4_9 (.A0(s_multi_12bit_0_3_23), .A1(scuba_vlo), 
        .B0(f_s_multi_12bit_0_2_23), .B1(scuba_vlo), .CI(co_t_multi_12bit_0_4_8), 
        .COUT(co_t_multi_12bit_0_4_9), .S0(rego_o_23), .S1());

    MULT2 multi_12bit_0_mult_0_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(multi_12bit_0_cin_lr_0), .P0(multi_12bit_0_pp_0_1), .P1(multi_12bit_0_pp_0_2), 
        .CO(mco));

    MULT2 multi_12bit_0_mult_0_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco), .P0(multi_12bit_0_pp_0_3), .P1(multi_12bit_0_pp_0_4), 
        .CO(mco_1));

    MULT2 multi_12bit_0_mult_0_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_1), .P0(multi_12bit_0_pp_0_5), .P1(multi_12bit_0_pp_0_6), 
        .CO(mco_2));

    MULT2 multi_12bit_0_mult_0_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_2), .P0(multi_12bit_0_pp_0_7), .P1(multi_12bit_0_pp_0_8), 
        .CO(mco_3));

    MULT2 multi_12bit_0_mult_0_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_3), .P0(multi_12bit_0_pp_0_9), .P1(multi_12bit_0_pp_0_10), 
        .CO(mco_4));

    MULT2 multi_12bit_0_mult_0_5 (.A0(DataA[10]), .A1(multi_12bit_0_mult_0_5_n2), 
        .A2(multi_12bit_0_mult_0_5_n1), .A3(scuba_vhi), .B0(DataB[1]), .B1(scuba_vhi), 
        .B2(scuba_vhi), .B3(scuba_vhi), .CI(mco_4), .P0(multi_12bit_0_pp_0_11), 
        .P1(multi_12bit_0_pp_0_12), .CO(mfco));

    MULT2 multi_12bit_0_mult_2_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(multi_12bit_0_cin_lr_2), .P0(multi_12bit_0_pp_1_3), .P1(multi_12bit_0_pp_1_4), 
        .CO(mco_5));

    MULT2 multi_12bit_0_mult_2_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_5), .P0(multi_12bit_0_pp_1_5), .P1(multi_12bit_0_pp_1_6), 
        .CO(mco_6));

    MULT2 multi_12bit_0_mult_2_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_6), .P0(multi_12bit_0_pp_1_7), .P1(multi_12bit_0_pp_1_8), 
        .CO(mco_7));

    MULT2 multi_12bit_0_mult_2_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_7), .P0(multi_12bit_0_pp_1_9), .P1(multi_12bit_0_pp_1_10), 
        .CO(mco_8));

    MULT2 multi_12bit_0_mult_2_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_8), .P0(multi_12bit_0_pp_1_11), .P1(multi_12bit_0_pp_1_12), 
        .CO(mco_9));

    MULT2 multi_12bit_0_mult_2_5 (.A0(DataA[10]), .A1(multi_12bit_0_mult_2_5_n2), 
        .A2(multi_12bit_0_mult_2_5_n1), .A3(scuba_vlo), .B0(DataB[3]), .B1(scuba_vhi), 
        .B2(scuba_vhi), .B3(DataB[2]), .CI(mco_9), .P0(multi_12bit_0_pp_1_13), 
        .P1(multi_12bit_0_pp_1_14), .CO(mfco_1));

    MULT2 multi_12bit_0_mult_4_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(multi_12bit_0_cin_lr_4), .P0(multi_12bit_0_pp_2_5), .P1(multi_12bit_0_pp_2_6), 
        .CO(mco_10));

    MULT2 multi_12bit_0_mult_4_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_10), .P0(multi_12bit_0_pp_2_7), .P1(multi_12bit_0_pp_2_8), 
        .CO(mco_11));

    MULT2 multi_12bit_0_mult_4_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_11), .P0(multi_12bit_0_pp_2_9), .P1(multi_12bit_0_pp_2_10), 
        .CO(mco_12));

    MULT2 multi_12bit_0_mult_4_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_12), .P0(multi_12bit_0_pp_2_11), .P1(multi_12bit_0_pp_2_12), 
        .CO(mco_13));

    MULT2 multi_12bit_0_mult_4_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_13), .P0(multi_12bit_0_pp_2_13), .P1(multi_12bit_0_pp_2_14), 
        .CO(mco_14));

    MULT2 multi_12bit_0_mult_4_5 (.A0(DataA[10]), .A1(multi_12bit_0_mult_4_5_n2), 
        .A2(multi_12bit_0_mult_4_5_n1), .A3(scuba_vlo), .B0(DataB[5]), .B1(scuba_vhi), 
        .B2(scuba_vhi), .B3(DataB[4]), .CI(mco_14), .P0(multi_12bit_0_pp_2_15), 
        .P1(multi_12bit_0_pp_2_16), .CO(mfco_2));

    MULT2 multi_12bit_0_mult_6_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(multi_12bit_0_cin_lr_6), .P0(multi_12bit_0_pp_3_7), .P1(multi_12bit_0_pp_3_8), 
        .CO(mco_15));

    MULT2 multi_12bit_0_mult_6_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_15), .P0(multi_12bit_0_pp_3_9), .P1(multi_12bit_0_pp_3_10), 
        .CO(mco_16));

    MULT2 multi_12bit_0_mult_6_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_16), .P0(multi_12bit_0_pp_3_11), .P1(multi_12bit_0_pp_3_12), 
        .CO(mco_17));

    MULT2 multi_12bit_0_mult_6_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_17), .P0(multi_12bit_0_pp_3_13), .P1(multi_12bit_0_pp_3_14), 
        .CO(mco_18));

    MULT2 multi_12bit_0_mult_6_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_18), .P0(multi_12bit_0_pp_3_15), .P1(multi_12bit_0_pp_3_16), 
        .CO(mco_19));

    MULT2 multi_12bit_0_mult_6_5 (.A0(DataA[10]), .A1(multi_12bit_0_mult_6_5_n2), 
        .A2(multi_12bit_0_mult_6_5_n1), .A3(scuba_vlo), .B0(DataB[7]), .B1(scuba_vhi), 
        .B2(scuba_vhi), .B3(DataB[6]), .CI(mco_19), .P0(multi_12bit_0_pp_3_17), 
        .P1(multi_12bit_0_pp_3_18), .CO(mfco_3));

    MULT2 multi_12bit_0_mult_8_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(multi_12bit_0_cin_lr_8), .P0(multi_12bit_0_pp_4_9), .P1(multi_12bit_0_pp_4_10), 
        .CO(mco_20));

    MULT2 multi_12bit_0_mult_8_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_20), .P0(multi_12bit_0_pp_4_11), .P1(multi_12bit_0_pp_4_12), 
        .CO(mco_21));

    MULT2 multi_12bit_0_mult_8_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_21), .P0(multi_12bit_0_pp_4_13), .P1(multi_12bit_0_pp_4_14), 
        .CO(mco_22));

    MULT2 multi_12bit_0_mult_8_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_22), .P0(multi_12bit_0_pp_4_15), .P1(multi_12bit_0_pp_4_16), 
        .CO(mco_23));

    MULT2 multi_12bit_0_mult_8_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_23), .P0(multi_12bit_0_pp_4_17), .P1(multi_12bit_0_pp_4_18), 
        .CO(mco_24));

    MULT2 multi_12bit_0_mult_8_5 (.A0(DataA[10]), .A1(multi_12bit_0_mult_8_5_n2), 
        .A2(multi_12bit_0_mult_8_5_n1), .A3(scuba_vlo), .B0(DataB[9]), .B1(scuba_vhi), 
        .B2(scuba_vhi), .B3(DataB[8]), .CI(mco_24), .P0(multi_12bit_0_pp_4_19), 
        .P1(multi_12bit_0_pp_4_20), .CO(mfco_4));

    MULT2 multi_12bit_0_mult_10_0 (.A0(multi_12bit_0_mult_10_0_n0), .A1(DataA[1]), 
        .A2(multi_12bit_0_mult_10_0_n1), .A3(DataA[2]), .B0(scuba_vhi), 
        .B1(DataB[10]), .B2(scuba_vhi), .B3(DataB[10]), .CI(multi_12bit_0_cin_lr_10), 
        .P0(multi_12bit_0_pp_5_11), .P1(multi_12bit_0_pp_5_12), .CO(mco_25));

    MULT2 multi_12bit_0_mult_10_1 (.A0(multi_12bit_0_mult_10_1_n0), .A1(DataA[3]), 
        .A2(multi_12bit_0_mult_10_1_n1), .A3(DataA[4]), .B0(scuba_vhi), 
        .B1(DataB[10]), .B2(scuba_vhi), .B3(DataB[10]), .CI(mco_25), .P0(multi_12bit_0_pp_5_13), 
        .P1(multi_12bit_0_pp_5_14), .CO(mco_26));

    MULT2 multi_12bit_0_mult_10_2 (.A0(multi_12bit_0_mult_10_2_n0), .A1(DataA[5]), 
        .A2(multi_12bit_0_mult_10_2_n1), .A3(DataA[6]), .B0(scuba_vhi), 
        .B1(DataB[10]), .B2(scuba_vhi), .B3(DataB[10]), .CI(mco_26), .P0(multi_12bit_0_pp_5_15), 
        .P1(multi_12bit_0_pp_5_16), .CO(mco_27));

    MULT2 multi_12bit_0_mult_10_3 (.A0(multi_12bit_0_mult_10_3_n0), .A1(DataA[7]), 
        .A2(multi_12bit_0_mult_10_3_n1), .A3(DataA[8]), .B0(scuba_vhi), 
        .B1(DataB[10]), .B2(scuba_vhi), .B3(DataB[10]), .CI(mco_27), .P0(multi_12bit_0_pp_5_17), 
        .P1(multi_12bit_0_pp_5_18), .CO(mco_28));

    MULT2 multi_12bit_0_mult_10_4 (.A0(multi_12bit_0_mult_10_4_n0), .A1(DataA[9]), 
        .A2(multi_12bit_0_mult_10_4_n1), .A3(DataA[10]), .B0(scuba_vhi), 
        .B1(DataB[10]), .B2(scuba_vhi), .B3(DataB[10]), .CI(mco_28), .P0(multi_12bit_0_pp_5_19), 
        .P1(multi_12bit_0_pp_5_20), .CO(mco_29));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    MULT2 multi_12bit_0_mult_10_5 (.A0(multi_12bit_0_mult_10_5_n0), .A1(multi_12bit_0_mult_10_5_n2), 
        .A2(DataA[11]), .A3(scuba_vlo), .B0(scuba_vhi), .B1(scuba_vhi), 
        .B2(DataB[11]), .B3(DataB[10]), .CI(mco_29), .P0(multi_12bit_0_pp_5_21), 
        .P1(multi_12bit_0_pp_5_22), .CO(mfco_5));

    assign rego_o_0 = f_multi_12bit_0_pp_0_0;
    assign rego_o_1 = f_multi_12bit_0_pp_0_1;
    assign rego_o_2 = f_s_multi_12bit_0_0_2;
    assign rego_o_3 = f_s_multi_12bit_0_0_3;
    assign rego_o_4 = s_multi_12bit_0_3_4;
    assign rego_o_5 = s_multi_12bit_0_3_5;
    assign rego_o_6 = s_multi_12bit_0_3_6;
    assign rego_o_7 = s_multi_12bit_0_3_7;


    // exemplar begin
    // exemplar attribute FF_75 GSR ENABLED
    // exemplar attribute FF_74 GSR ENABLED
    // exemplar attribute FF_73 GSR ENABLED
    // exemplar attribute FF_72 GSR ENABLED
    // exemplar attribute FF_71 GSR ENABLED
    // exemplar attribute FF_70 GSR ENABLED
    // exemplar attribute FF_69 GSR ENABLED
    // exemplar attribute FF_68 GSR ENABLED
    // exemplar attribute FF_67 GSR ENABLED
    // exemplar attribute FF_66 GSR ENABLED
    // exemplar attribute FF_65 GSR ENABLED
    // exemplar attribute FF_64 GSR ENABLED
    // exemplar attribute FF_63 GSR ENABLED
    // exemplar attribute FF_62 GSR ENABLED
    // exemplar attribute FF_61 GSR ENABLED
    // exemplar attribute FF_60 GSR ENABLED
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
