/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 1.6 */
/* Thu Sep 26 22:29:12 2024 */

/* parameterized module instance */
nco __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ), .Cosine( ));
